# Generated by Django 4.2.4 on 2024-02-25 08:15

import StatTrackingBackend.models.user_models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='caffeine/')),
            ],
        ),
        migrations.CreateModel(
            name='CaffeineCommonServing',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='caffeine/')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyUseCase',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='money/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('access', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Caffeine', 'Access Caffeine'), ('TooLate', 'Access Too Late'), ('Sleep', 'Access Sleep'), ('Money', 'Access Money')], default='Caffeine,TooLate,Sleep', max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', StatTrackingBackend.models.user_models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[512, 512], upload_to='profile_pictures/')),
                ('bio', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verified_email', models.BooleanField(blank=True, default=False)),
                ('email_code', models.CharField(blank=True, max_length=10)),
                ('password_code', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TooLate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('event', models.CharField(max_length=50)),
                ('excuse', models.CharField(max_length=200)),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted_logs', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('hours_slept', models.FloatField()),
                ('quality', models.SmallIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('money_spent', models.FloatField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StatTrackingBackend.moneyusecase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaffeineType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('caffeine', models.FloatField()),
                ('commonServing', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='caffeine/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StatTrackingBackend.caffeinecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Caffeine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('drink_size', models.FloatField()),
                ('drink_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caffeine_logs', to='StatTrackingBackend.caffeinetype')),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted_logs', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TooLateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='too_late_ratings', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='StatTrackingBackend.toolate')),
            ],
            options={
                'unique_together': {('rater', 'target')},
            },
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 25, 9, 15, 14, 429670))),
                ('message', models.CharField(blank=True, max_length=256)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Caffeine', 'Access Caffeine'), ('TooLate', 'Access Too Late'), ('Sleep', 'Access Sleep'), ('Money', 'Access Money')], max_length=256)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
