# Generated by Django 4.2.4 on 2023-10-04 08:13

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Coffee', 'Access Coffee'), ('TooLate', 'Access Too Late'), ('Horny', 'Access Horny')], default='Coffee,TooLate', max_length=256),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 4, 10, 13, 22, 988788)),
        ),
    ]
