# Generated by Django 4.2.4 on 2023-12-07 22:44

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caffeine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='horny',
            name='id',
        ),
        migrations.RemoveField(
            model_name='toolate',
            name='id',
        ),
        migrations.AddField(
            model_name='caffeine',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='horny',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='toolate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 7, 23, 44, 5, 400817)),
        ),
    ]
