# Generated by Django 4.2.4 on 2023-09-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0002_remove_user_rights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'default_permissions': ('access',)},
        ),
        migrations.AlterModelOptions(
            name='horny',
            options={'default_permissions': ('access',)},
        ),
        migrations.AlterModelOptions(
            name='toolate',
            options={'default_permissions': ('access',)},
        ),
    ]
