# Generated by Django 4.2.4 on 2023-10-15 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0002_user_access_alter_friendshiprequest_sent_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('caffeine', models.FloatField()),
                ('commonServing', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 15, 18, 43, 53, 909702)),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='coffee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StatTrackingBackend.coffeetype'),
        ),
    ]
