# Generated by Django 4.2.4 on 2023-10-15 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0003_coffeetype_alter_friendshiprequest_sent_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeetype',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 15, 19, 33, 38, 749495)),
        ),
    ]
