# Generated by Django 4.2.4 on 2023-10-15 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0004_coffeetype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetype',
            name='commonServing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 15, 21, 54, 15, 469674)),
        ),
    ]
