# Generated by Django 4.2.4 on 2023-10-16 17:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0005_alter_coffeetype_commonserving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caffeine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('drink_size', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaffeineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('caffeine', models.FloatField()),
                ('commonServing', models.IntegerField()),
                ('image', models.ImageField(height_field=256, upload_to='', width_field=256)),
            ],
        ),
        migrations.AlterField(
            model_name='friendship',
            name='access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Caffeine', 'Access Caffeine'), ('TooLate', 'Access Too Late'), ('Horny', 'Access Horny')], max_length=256),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 16, 19, 52, 53, 589649)),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Caffeine', 'Access Caffeine'), ('TooLate', 'Access Too Late'), ('Horny', 'Access Horny')], default='Caffeine,TooLate', max_length=256),
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='CoffeeType',
        ),
        migrations.AddField(
            model_name='caffeine',
            name='drink_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caffeine_logs', to='StatTrackingBackend.caffeinetype'),
        ),
        migrations.AddField(
            model_name='caffeine',
            name='logger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caffeine',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
