# Generated by Django 4.2.4 on 2023-10-16 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0006_caffeine_caffeinetype_alter_friendship_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeinetype',
            name='category',
            field=models.CharField(choices=[('COF', 'Coffee'), ('BEV', 'Beverage'), ('TEA', 'Tea')], default='COF', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caffeinetype',
            name='image',
            field=models.ImageField(blank=True, height_field=256, null=True, upload_to='', width_field=256),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 16, 20, 17, 16, 814965)),
        ),
    ]
