# Generated by Django 4.2.4 on 2023-10-16 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0007_caffeinetype_category_alter_caffeinetype_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, height_field=256, null=True, upload_to='', width_field=256)),
            ],
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 16, 20, 25, 0, 891683)),
        ),
        migrations.AlterField(
            model_name='caffeinetype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StatTrackingBackend.caffeinecategory'),
        ),
    ]
