# Generated by Django 4.2.4 on 2023-11-13 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0008_caffeinecategory_alter_friendshiprequest_sent_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineCommonServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='caffeine/')),
            ],
        ),
        migrations.AlterField(
            model_name='caffeinecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caffeine/'),
        ),
        migrations.AlterField(
            model_name='caffeinetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caffeine/'),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 13, 17, 33, 38, 98496)),
        ),
    ]
