# Generated by Django 4.2.4 on 2023-11-30 23:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0009_caffeinecommonserving_alter_caffeinecategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verified_email', models.BooleanField(blank=True, default=False)),
                ('email_code', models.CharField(max_length=10)),
                ('password_code', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='debug@web.de', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 1, 0, 44, 49, 184873)),
        ),
    ]
