# Generated by Django 4.2.4 on 2023-12-03 00:59

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('StatTrackingBackend', '0011_userprofile_alter_friendshiprequest_sent_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='sent_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 3, 1, 59, 10, 566130)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[512, 512], upload_to='profile_pictures/'),
        ),
    ]
